### ISSUE TITLE
do we also need a sample source ID?

### ISSUE THREAD

**Issue by andrewsu** [cvisb/sample_viewer_web#1]
https://github.com/cvisb/sample_viewer_web/blob/5e7fd62bf16a80a69af461d55a5b9dd6abc6c1e5/sample-viewer-api/src/static/schemas/sample-schema-v1.0.1.json#L24

per discussion 2018-10-18

**Comment by andrewsu** [comment]
for example, which PBMC sample is a viralRNA sample derived from?

**Comment by flaneuse** [comment]
Fixed

**Comment by andrewsu** [comment]
8c87d45bd0f42f669421239b162ff31821535f6b
